project:
  type: book

execute:
  freeze: auto

book:
  page-navigation: true
  title: "StratMystiqPro Documentation"
  description: "StratMystiqPro - A tool for quick strategic insights"
  author: "Team 1"
  site-url: "https://LMM-Team1.github.io/documentation/"
  repo-url: https://github.com/LLM-Team1/documentation
  repo-actions: [edit, issue]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  sidebar:
    logo: "/images/StratMystiq-Icon.png"
    search: true
  page-footer:
    left: |
      © Team 1, 2024
    center:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: intro.qmd  
    right:
      - icon: bi bi-github
        href: https://github.com/LLM-Team1/StratMystiqPro
#    background: "#325b74"    
  chapters:
    - index.qmd
    - intro.qmd
    - part: Business Relevance
      chapters:
        - usecase.qmd
        - userPersona.qmd
        - bmc.qmd
        - strategyMap.qmd
        - valueProposition.qmd
    - part: System Design
      chapters:
        - RAGpipeline.qmd
        - RAGevaluation.qmd
        - backendArchitecture.qmd
        - frontendArchitecture.qmd
    - part: Usage
      chapters:
        - deployment.qmd
        - userManual.qmd
    - references.qmd

format:
  html:
    toc: true
    number-sections: true
    number-depth: 2
    theme:
      light: [cosmo, style/style.scss]
      dark: [cosmo, style/style.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

bibliography: references.bib