# Introduction and Project Overview

In this project our goal was to build a Large Language Model (LLM) application. Therefore we identified a use case to
make use of a LLM. Based on that use case, we developed a business model canvas to define the foundation of our
SaaS-start up.

Together with Mr. Kirenz we defined our [use case](https://llm-team1.github.io/documentation/usecase.html)
to then created a business model. Our use case was based on the idea of finding a way to make business
analysis quick and easy for a wide range of potential customers. After that we constructed the business model around
this use case. You can read more about the use case identification and modelling of our Business Model Canvas
[here](https://llm-team1.github.io/documentation/bmc.html). For a more visual understanding of our startups' next goals
we created a [strategy map](https://llm-team1.github.io/documentation/strategyMap.html) showing the directions our
start up could go in the future.

Our solution takes the findings of our use case identification and transforms them into a software as a service
(SaaS) solution. This solution provides an analysis tool for [our customers](https://llm-team1.github.io/documentation/userPersona.html)
to fulfill our value propositions.

We are using a [Retrieval Augmented Generation (RAG) pipeline](https://llm-team1.github.io/documentation/RAGpipeline.html) to load and retrieve
the needed information (coming from business reports) from our vector store. We encountered different obstacles
on our way, therefore we decided to customize the basic RAG pipline to deal with image/table recognition and at the
same time improve answer precision by utilizing pre- and post-retrieval steps.

We used multiple [evaluation methods](https://llm-team1.github.io/documentation/RAGevaluation.html) to evaluate the
performance of our customized RAG. The main goal was to identify the overall performance of our custom RAG
compared to the basic RAG. At the same time we evaluated the best chunk size for both RAGs.

We also developed a user friendly [frontend](https://llm-team1.github.io/documentation/frontendArchitecture.html) to
enable our customers to navigate between their business reports, analyses, and comparisons. Focus here was especially
on the presentation of the extensive information in the SWOT analyses.

Finally we documented the whole project in the documentation that you are currently reading.