# Introduction and Project Overview

In this module we got the task to identify a use case from a business model canvas to improve a business unit or
different part of an existing company.

Together with Mr. Kirenz we decided to first define our [use case](https://llm-team1.github.io/documentation/usecase.html)
to then create a business model from there on. Our use case was based on the idea of finding a way to make business
analysis quick and easy for a wide range of potential customers. After that we constructed the business model around
this use case. You can read more about the use case identification and modelling of our Business Model Canvas
[here](https://llm-team1.github.io/documentation/bmc.html). For a more visual understanding of our startups' next goals
we created a [strategy map](https://llm-team1.github.io/documentation/strategyMap.html) showing the directions our
start up would go in the future.

Our solution takes the findings of our use case identification and transform them into a software as a service
(SaaS) solution. This solution provides an analysis tool for [our customers](https://llm-team1.github.io/documentation/userPersona.html)
to fulfill our value propositions.

We are using a [Retrieval Augmented Generation (RAG) pipeline](/documentation/RAGpipeline.html) to load and retrieve
the needed information (coming from business reports) in/from our vector store. We encountered different obstacles
on our way, therefore we decided to customize the basic RAG pipline to deal with image/ table recognition and at the
same time improve answer precision by using a multi query approach.

We used multiple [evaluation methods](https://llm-team1.github.io/documentation/RAGevaluation.html) to evaluate the
performance of our customized RAG. The main goal was here to identify the overall performance of our custom RAG
compared to the basic RAG. At the same time we evaluated the best chunk size for both RAGs. The best solution was
our custom RAG, using the chunk size of 900.

We also developed a user friendly [frontend](https://llm-team1.github.io/documentation/frontendArchitecture.html) to
enable our customers to navigate between their business reports, analyses, and comparisons. Focus here was especially
on the presentation of the extensive information in the SWAT analyses.

Finally we created a comprehensive manual on [how to deploy our application](https://llm-team1.github.io/documentation/deployment.html)
and [how to use our application](https://llm-team1.github.io/documentation/userManual.html).
